en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} CRS Project. All Rights Reserved."
  title: "CRS Project"
  description: "The first line of defense"
  params:
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Join"
      link: "/example-page/"
    footer_cta:
      text: "Join us"
      link: "/example-page/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 1
    - identifier: "videos"
      name: "Videos"
      url: "/videos/"
      weight: 2
    - identifier: "docs"
      name: "Documentation"
      url: "/docs/"
      weight: 3
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 4
    - identifier: "Support"
      name: "Support"
      url: "/support/"
      weight: 5
    - identifier: "donate"
      name: "Donate"
      url: "https://owasp.org/donate/?reponame=www-project-modsecurity-core-rule-set&title=OWASP+ModSecurity+Core+Rule+Set"
      weight: 6
    - identifier: "sponsors"
      name: "Sponsors"
      url: "/sponsors"
      weight: 6
