######################## production configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL: "https://coreruleset.github.io/website/"
googleAnalytics: 
enableRobotsTXT: true
build:
  writeStats: true
